In [1]:
import numpy as np
from models.nODE import nODE, make_nODE_from_parameters
import scipy.io

In [2]:
def distribute_parameters(param,adj):
    W1 = np.zeros((adj.shape[0],adj.shape[1]))
    k = 0
    for i in range(0, adj.shape[0]):
        for j in range(0, adj.shape[1]):
            if adj[i,j] > 0:
                W1[i,j] = param[k]
                k += 1

    gamma = np.zeros(adj.shape[0])
    for i in range(0, adj.shape[0]):
        gamma[i] = -param[k]
        k += 1

    b2 = np.zeros(adj.shape[0])
    for i in range(0, adj.shape[0]):
        b2[i] = param[k]
        k += 1
        
    b1 = np.zeros(adj.shape[0])
    for i in range(0, adj.shape[0]):
        b1[i] = param[k]
        k += 1

    W2 = np.zeros((adj.shape[0],adj.shape[1]))
    for i in range(0, adj.shape[0]):
        for j in range(0, adj.shape[1]):
            if i == j:
                W2[i,j] = param[k]
                k += 1
    
    return W1, gamma, b1, b2, W2


In [3]:
param1 = np.loadtxt('data/dyn_bifurcating/fit_cluster0_2_3.txt')
param2 = np.loadtxt('data/dyn_bifurcating/fit_cluster0.txt')

adj1 = scipy.io.loadmat('data/dyn_bifurcating/net.mat')['Aref']
adj1[2,3] = 0
adj2 = scipy.io.loadmat('data/dyn_bifurcating/net.mat')['Aref']

(W1_1, gamma_1, b1_1, b2_1, W2_1) = distribute_parameters(param1,adj1)
(W1_2, gamma_2, b1_2, b2_2, W2_2) = distribute_parameters(param2,adj2)

# make_nODE_from_parameters(Gamma, Win=None, bin=None, Wout=None, bout=None)
nODE1 = make_nODE_from_parameters(gamma_1, W1_1, b1_1, W2_1, b2_1)
nODE2 = make_nODE_from_parameters(gamma_2, W1_2, b1_2, W2_2, b2_2)

In [4]:
from models.ranking import rank

rank(nODE1,nODE2)

[0.6984886635569303, 0.2959223985671997, 1.0]

In [5]:
param1 = np.loadtxt('data/dyn_bifurcating/fit_cluster0_2_3_improved.txt')
param2 = np.loadtxt('data/dyn_bifurcating/fit_cluster0.txt')

adj1 = scipy.io.loadmat('gae_results/dyn_bifurcating_2_3.mat')['inferred_adj']
adj1 = (adj1>0.5).astype(int)
adj2 = scipy.io.loadmat('data/dyn_bifurcating/net.mat')['Aref']

(W1_1, gamma_1, b1_1, b2_1, W2_1) = distribute_parameters(param1,adj1)
(W1_2, gamma_2, b1_2, b2_2, W2_2) = distribute_parameters(param2,adj2)

# make_nODE_from_parameters(Gamma, Win=None, bin=None, Wout=None, bout=None)
nODE1 = make_nODE_from_parameters(gamma_1, W1_1, b1_1, W2_1, b2_1)
nODE2 = make_nODE_from_parameters(gamma_2, W1_2, b1_2, W2_2, b2_2)

FileNotFoundError: [Errno 2] No such file or directory: 'gae_results/dyn_bifurcating_2_3.mat'

In [6]:
from models.ranking import rank

rank(nODE1,nODE2)

[0.6984886635569303, 0.2959223985671997, 1.0]

In [6]:
param1

array([ 3.41098353e+00,  1.57791702e+00, -1.57407168e-04, -3.40206216e+00,
        3.57352460e+00, -1.54656453e+00,  2.26729037e+00, -3.47607141e+00,
       -4.08427932e-04,  6.54934745e-04,  9.06295442e-05,  3.28388033e+00,
        7.04879412e+00,  2.50184559e+00,  2.97630495e+00,  4.14093569e-01,
        3.18180934e+00,  2.86568020e+00,  1.44189480e+00,  8.78918386e+00,
        1.44935393e+00,  4.85638637e+00,  5.22585027e+00,  3.83348141e+00,
        1.70204866e+00,  2.67552896e+00, -3.39376210e+00, -8.22702305e-01,
       -1.37213608e+00, -4.95585940e-01, -1.41125669e+00,  2.77647003e+00,
        1.40063024e+00,  8.74599630e+00,  2.14740600e+00,  1.85896758e+00,
        5.18267122e+00,  3.54069104e+00,  1.59048491e+00])

In [17]:
nODE1.inside_weights.weight

Parameter containing:
tensor([[ 0.0000e+00,  3.4110e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.5779e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, -1.5741e-04,
          0.0000e+00,  0.0000e+00],
        [-3.4021e+00,  0.0000e+00,  0.0000e+00,  3.5735e+00, -1.5466e+00,
          2.2673e+00, -3.4761e+00],
        [-4.0843e-04,  0.0000e+00,  0.0000e+00,  6.5493e-04,  9.0630e-05,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00]], requires_grad=True)

In [30]:
nODE1.adjacency_matrix()

tensor([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., -1.,  0.,  0.],
        [-1.,  0.,  0.,  1., -1.,  1., -1.],
        [-1.,  0.,  0.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [31]:
np.abs(nODE2.adjacency_matrix()) - np.abs(nODE1.adjacency_matrix())

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.linalg.norm(np.abs(nODE2.adjacency_matrix()) - np.abs(nODE1.adjacency_matrix()))/np.linalg.norm(np.abs(nODE1.adjacency_matrix()))

0.30151135

In [34]:
np.linalg.norm(np.abs(nODE1.adjacency_matrix()))

3.3166249

In [35]:
np.linalg.norm(np.abs(nODE2.adjacency_matrix()) - np.abs(nODE1.adjacency_matrix()))

1.0

In [36]:
true_network = np.abs(nODE1.adjacency_matrix())
found_network = np.abs(nODE2.adjacency_matrix())
ranking_network = 1 - np.linalg.norm(true_network - found_network) / np.max([1., np.linalg.norm(true_network)])

In [37]:
ranking_network

0.6984886635569303